### ISSUE TITLE
刚开始有权限,可以正常执行.然后去把权限禁掉.可是依然走了授权成功的回调

### ISSUE THREAD

**Issue by imgod1** [hongyangAndroid/MPermissions#13]
问题描述:
app刚安装好,点击按钮.检查权限.如果有权限则进入图片连选界面(鸿扬大神的高仿微信那个),这个时候可以读取到图片,然后进app的设置详情权限详情界面,看读写存储的权限都是允许的
然后把读写存储权限都禁止,然后重新打开app,点击按钮.依然能进入图片连选activity,提示暂无外部存储,这是怎么回事啊?按理说不应该走授权失败的那个回调吗?还请大神解惑,不胜感激
机型:zuk z2 ,zui 2.0.079

**Comment by hongyangAndroid** [comment]
这个机型我不太了解，国产机器大多都内置了权限管理，对于Android提供的机制，基本上都是直接返回true，等到你真正使用需要权限的行为时候，会使用它自带的权限管理来进行提示。

如果需要测试，建议拿模拟器或者Nexus系列机子试试~

**Comment by imgod1** [comment]
鸿扬大神.能给个魔教群吗..想进组织了.csdn上提供的群都满了..

**Comment by hongyangAndroid** [comment]
群号：497438697

**Comment by imgod1** [comment]
3q very much

**Comment by git-cncoder** [comment]
我用魅族手机(魅蓝3S)测试就有这个问题， 魅族5.0的系统内置了权限管理，在弹出框选择拒绝了，走的还是成功的回调，调用拨打电话的代码没有反应。有什么好的办法解决吗？

**Comment by imgod1** [comment]
走成功的回调后再检查一下权限吧.如果有直接todo,没有的话友情提示...

**Comment by git-cncoder** [comment]
现在不知道魅族内置权限的检查方法是什么，用这个检查是检测清单文件里面的永远返回的是0 PERMISSION_GRANTED 
` int selfPermission = PermissionChecker.checkSelfPermission(this, Manifest.permission.CALL_PHONE);
        LogUtils.e("requestSdcardSuccess" + selfPermission);`

控制台输出的是如下：提示了不能启动打电话的Intent，如果能有个办法判断就好了。这样点击拨打电话没反应的交互很不好。
```
E/LogUtils: requestSdcardSuccess0
E/Instrumentation: User denied to start activity with intent: Intent { act=android.intent.action.CALL dat=tel:xxxxx }
```

**Comment by imgod1** [comment]
试试这个
PackageManager pm = getPackageManager();  
        boolean permission = (PackageManager.PERMISSION_GRANTED ==   
                pm.checkPermission("android.permission.RECORD_AUDIO", "packageName"));  
        if (permission) {  
            showToast("有这个权限");  
        }else {  
            showToast("木有这个权限");  
        }  
如果可以那最好.如果还不行..那还真是日了狗了...

**Comment by git-cncoder** [comment]
嗯呢，还是不行呢，会执行showToast("有这个权限");这个方法。
果然定制的最难搞了。猜测 是因为6.0版本之前可能检测的是有没有在清单文件AndroidManifest.xml中注册权限，在Android studio自带的模拟器上面是直接拨打电话的，还是国产机器内置惹的祸额。不返回个失败的判断，提示用户去设置里面开启权限，比没反应好多了。可能是我没找到这类的方法吧。我再尝试一下其他方法，谢谢你的解答。 成功了M你。

**Comment by imgod1** [comment]
大兄弟.保重...

**Comment by IsSwm** [comment]
@imgod1 @hongyangAndroid 
鸿洋大神，如果有时间可以增加一下对于国产内置的权限管理，被拒绝了执行@PermissionGrant下的方法而不执行PermissionDenied下的方法。相信对于6.0以下应该是一个有用的适配。
已解决,try,catch一下enforceCallingPermission。
```
 try {
            getApplicationContext().enforceCallingPermission(Manifest.permission.CALL_PHONE, "error message");
        } catch (RuntimeException e) {
            // 打印的错误信息， 在这里可以提醒用户去开启某个权限才可以使用某个功能或其它的。
            LogUtils.e(e.toString());
        }
````
输出的日志
```
E/LogUtils: java.lang.SecurityException: error message: uid 10282 does not have android.permission.CALL_PHONE.
```

**Comment by git-cncoder** [comment]
写了折中的办法。。
http://www.jianshu.com/p/64b50a3efd16
