### ISSUE TITLE
不能和ButterKnife7.0.1 一起使用

### ISSUE THREAD

**Issue by Raynor999** [hongyangAndroid/MPermissions#2]
com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
    File1: E:\MJMHCode\building\libs\mpermissions.jar
    File2: C:\Users\Administrator.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\7.0.1\d5d13ea991eab0252e3710e5df3d6a9d4b21d461\butterknife-7.0.1.jar

**Comment by hongyangAndroid** [comment]
多谢反馈，已经上传到jcenter，按照下列方式添加依赖即可。

```
dependencies {
    apt 'com.zhy:mpermission-compiler:1.0.0'
    compile 'com.zhy:mpermission-api:1.0.0'
}
```
