### ISSUE TITLE
用的最新的自带gradle，com.android.tools.build:gradle:2.0.0-beta6，报以下错误

### ISSUE THREAD

**Issue by zhaohongbogit** [hongyangAndroid/MPermissions#4]
Error:(115, 0) Gradle DSL method not found: 'apt()'
Possible causes:<ul><li>The project '' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by hongyangAndroid** [comment]
project's build.gradle

buildscript {
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}
module's buid.gradle

apply plugin: 'com.neenbedankt.android-apt'

dependencies {
    apt 'com.zhy:mpermission-compiler:1.0.0'
    compile 'com.zhy:mpermission-api:1.0.0'
}

**Comment by zhaohongbogit** [comment]
已解决，没有安装apt插件
