### ISSUE TITLE
混淆报错

### ISSUE THREAD

**Issue by zhaohongbogit** [hongyangAndroid/MPermissions#5]
有没有考虑过混淆之后。我发现找不到相关类，增加如下代码依然有问题
# permission-lib,权限混淆

-dontwarn com.zhy.m.permission.**
-keep class com.zhy.m.permission.*\* { _;}
-keep interface com.zhy.m.permission._\* { *; }
求助解决，急用

**Comment by hongyangAndroid** [comment]
```
-dontwarn com.zhy.m.**
-keep class com.zhy.m.** {*;}
-keep interface com.zhy.m.** { *; }
-keep class **$$PermissionProxy { *; }
```

**Comment by zhaohongbogit** [comment]
已解决问题，这个PermissionProxy免混淆多加了一个点，哈哈
